# high level tests when push to `main`
name: Tests

on:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip install --upgrade pip wheel
      - run: pip install bandit flake8 flake8-2020 flake8-bugbear
                         flake8-comprehensions safety
      - run: bandit --recursive --skip B101 .   # B101 is assert statements
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: pip install --editable . || pip install .

      # testing requirements
      - run: pip install pytest pytest-asyncio looptime toml
      - run: pytest .
      - run: safety check
